model_name: klue/roberta-large
batch_size: 16
max_epoch: 4
# lr_scheduler: cosine_annealing
# shuffle: true
learning_rate: 1.8e-05
train_path: ./dataset/train/train.csv
dev_path: ./dataset/train/train.csv
test_path: ./dataset/test/test_data.csv
weight_decay: 0.01
# warm_up_ratio: 0.1
loss_func: FL
exp_theme: "focal-loss"